version: "3"

services:
  proxy:
    image: nginx:1.15-alpine
    container_name: proxy
    ports:
      - 80:80
      - "443"
    networks: 
      - production-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - biblioteca-pessoal

  biblioteca-pessoal:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ".:/www"
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    env_file: .env
    networks: 
      - production-network

networks:
  production-network:
    driver: bridge