name: deploy

on:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: Matheus73/Trabalho-Individual-2021-2/.github/workflows/main.yml@main

  deploy:
    needs: ci

    name: cd
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      -
        name: build-push-action
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:aplicacao"
          push: true
          tags: bigode73/biblioteca-pessoal:latest
